const GET_AC_STATUS = 'GET_AC_STATUS';
const GET_AC_STATUS_CACHE = 'GET_AC_STATUS_CACHE';
const UPDATE_AC_STATUS = 'UPDATE_AC_STATUS';
const SET_STATUS_AC_MODE = 'SET_STATUS_AC_MODE';
const SET_STATUS_AC_SPEED = 'SET_STATUS_AC_SPEED';
const SET_STATUS_SWING = 'SET_STATUS_SWING';
const SET_STATUS_TEMPERATURE = 'SET_STATUS_TEMPERATURE';
const SET_STATUS_POWER = 'SET_STATUS_POWER';

const SET_NON_STATUS_AC_MODE = 'SET_NON_STATUS_AC_MODE';
const SET_NON_STATUS_AC_SPEED = 'SET_NON_STATUS_AC_SPEED';
const SET_NON_STATUS_SWING = 'SET_NON_STATUS_SWING';
const SET_NON_STATUS_TEMPERATURE_UP = 'SET_NON_STATUS_TEMPERATURE_UP';
const SET_NON_STATUS_TEMPERATURE_DOWN = 'SET_NON_STATUS_TEMPERATURE_DOWN';
const SET_NON_STATUS_POWER = 'SET_NON_STATUS_POWER';

const GET_AC_DAY_ELEC = 'GET_AC_DAY_ELEC';
const GET_AC_MONTH_ELEC = 'GET_AC_MONTH_ELEC';
const GET_AC_SETTINGS = 'GET_AC_SETTINGS';
const UPDATE_AC_SETTINGS = 'UPDATE_AC_SETTINGS';

export {
  GET_AC_STATUS,
  UPDATE_AC_STATUS,
  GET_AC_STATUS_CACHE,
  SET_STATUS_AC_MODE,
  SET_STATUS_AC_SPEED,
  SET_STATUS_SWING,
  SET_STATUS_TEMPERATURE,
  SET_STATUS_POWER,
  SET_NON_STATUS_AC_MODE,
  SET_NON_STATUS_AC_SPEED,
  SET_NON_STATUS_SWING,
  SET_NON_STATUS_TEMPERATURE_UP,
  SET_NON_STATUS_TEMPERATURE_DOWN,
  SET_NON_STATUS_POWER,
  GET_AC_DAY_ELEC,
  GET_AC_MONTH_ELEC,
  GET_AC_SETTINGS,
  UPDATE_AC_SETTINGS
};
