const CHANGE_TEXT_TEST = 'CHANGE_TEXT_TEST';
const SHOW_MORE_DIALOG = 'SHOW_MORE_DIALOG'; // 安卓显示更多弹窗
const UPDATE_REMOTE = 'UPDATE_REMOTE';
const UPDATE_REMOTE_MODEL = 'UPDATE_REMOTE_MODEL';
const UPDATE_REMOTE_MODEL_CACHE = 'UPDATE_REMOTE_MODEL_CACHE';

export {
  CHANGE_TEXT_TEST,
  SHOW_MORE_DIALOG,
  UPDATE_REMOTE,
  UPDATE_REMOTE_MODEL,
  UPDATE_REMOTE_MODEL_CACHE
};